version: '3'
services:
  smart-chili-factory-cron:
    restart: always
    container_name: smart-chili-factory-cron
    build:
      context: ./cron/
    environment:
     - LOG_DIR=/var/log/smart-chili-factory
     - SHOTS_DIR=/var/smart-chili-factory/shots
    volumes:
      - /tmp/smart-chili-factory:/tmp/
      - /var/smart-chili-factory/:/var/smart-chili-factory/
      - ./cron/5min/:/etc/periodic/5min/:ro
    env_file:
      - env/secrets.env