version: '3'
services:
  smart-chili-factory-cron:
    restart: always
    container_name: smart-chili-factory-cron
    build:
      context: ./modules/cron_tasks
    environment:
     - LOG_DIR=/var/log/smart-chili-factory/logs
     - SHOTS_DIR=/var/smart-chili-factory/shots
     - TIMELAPSES_DIR=/var/smart-chili-factory/timelapses
     - SCRIPTS_DIR=/var/smart-chili-factory/scripts
     - TIMESTAMP_PATTERN=%Y%m%d%H%M%S
    volumes:
      - /tmp/smart-chili-factory:/tmp/
      - /var/smart-chili-factory/:/var/smart-chili-factory/
      - ./scripts/:/var/smart-chili-factory/scripts/
    env_file:
      - env/secrets.env