#!/bin/bash
FFMPEG_ARGS_FILE=$1
OUT_FILE=$2
TYPE=$3
TIMESTAMP=$4
CAM_NUM=$5

if [[ -z $FFMPEG_ARGS_FILE ]]; then
    echo "FFMPEG_ARGS_FILE as 1st argument is mandatory";
    exit 1;
fi
if [[ -z $OUT_FILE ]]; then
    echo "OUT_FILE as 2nd argument is mandatory";
    exit 1;
fi

if [[ -z $TYPE ]]; then
    echo "TYPE as 3th is mandatory";
    exit 1;
fi
if [[ -z $TIMESTAMP ]]; then
    echo "TIMESTAMP as 4th argument is mandatory";
    exit 1;
fi

CAM_NUM=${CAM_NUM:-cam0}

ffmpeg -f concat -safe 0 -r 30 -i "$FFMPEG_ARGS_FILE" -s:v 1980x1080 -c:v libx264 -crf 17 -pix_fmt yuv420p -r 30 $OUT_FILE -nostats -hide_banner -v 0 -loglevel quiet
