#!/bin/bash
TYPE="daily"
YEAR=$(date +"%Y")
CAM0="cam0"
TL_DIR=$TIMELAPSES_DIR/$TYPE/$YEAR
if [[ ! -d $TL_DIR ]]; then
  mkdir -p $TL_DIR \
  && echo "Created $TL_DIR"
fi

TIMESTAMP=$(date +"$TIMESTAMP_PATTERN")
OUT_FILE_NAME="${CAM0}_${TIMESTAMP}"
OUT_FILE=$TL_DIR/$OUT_FILE_NAME.mp4
FFMPEG_INPUT_FILE="/tmp/ffmpegargs_${TYPE}_timelapse_${OUT_FILE_NAME}.txt"

find $SHOTS_DIR/*/*.jpg -type f -ctime -1 | sort | awk '{print "file \x27"$0"\x27"}' > $FFMPEG_INPUT_FILE

bash $SCRIPTS_DIR/_make_timelapse $FFMPEG_INPUT_FILE $OUT_FILE $TYPE $TIMESTAMP $CAM0 \
  && echo "Saved $TYPE timelapse \"$OUT_FILE\""  \
  && rm -rf $FFMPEG_INPUT_FILE
