#!/bin/bash
TYPE="weekly"
YEAR=$(date +"%Y")
CAM0="cam0"
TL_DIR=$TIMELAPSES_DIR/$TYPE/$YEAR
if [[ ! -d $TL_DIR ]]; then
  mkdir -p $TL_DIR \
  && echo "Created $TL_DIR"
fi

TIMESTAMP=$(date +"$TIMESTAMP_PATTERN")
OUT_FILE_NAME="${CAM0}_${TIMESTAMP}"
OUT_FILE=$TL_DIR/$OUT_FILE_NAME.mp4
ffmpeg_input_file="/tmp/ffmpegargs_${TYPE}_timelapse_${OUT_FILE_NAME}.txt"

bash $SCRIPTS_DIR/_prepare_input_file $ffmpeg_input_file $SHOTS_DIR 6 0 "10:00:00" "17:00:00" \
  && bash $SCRIPTS_DIR/_make_timelapse $ffmpeg_input_file $OUT_FILE $TYPE $TIMESTAMP $CAM0 \
    && echo "Saved $TYPE timelapse \"$OUT_FILE\""  \
    && rm -rf $ffmpeg_input_file